import {fetchAllToDo as _fetchAllToDo, addToDo, ToDo, validateToDoJs} from "shared"
import {Suspense, use, useState, useTransition} from "react";

function ToDoList({ todosPromise }: { todosPromise: Promise<ReadonlyArray<ToDo>> }) {
    const todos = use(todosPromise)
    return (
        <ul className="space-y-3">
            {todos.map((todo) => (
                <li key={todo.id} className="bg-white p-4 border border-slate-200 rounded-xl shadow-sm flex justify-between items-center transition-all hover:border-blue-200 hover:shadow-md">
                    <span className="text-slate-700 font-medium">{todo.content}</span>
                    <span className="text-slate-400 text-xs font-mono bg-slate-50 px-2 py-1 rounded-md">ID: {todo.id}</span>
                </li>
            ))}
            {todos.length === 0 && (
                <div className="text-center py-10 text-slate-400 italic">
                    No tasks found. Add one above!
                </div>
            )}
        </ul>
    )
}

export default function App() {
    const [todosPromise, setTodosPromise] = useState(() => _fetchAllToDo())
    const [content, setContent] = useState("")
    const [isPending, startTransition] = useTransition()
    const [error, setError] = useState<string | null>(null)

    const handleAdd = async (e: React.FormEvent) => {
        e.preventDefault()
        setError(null)

        const trimmedContent = content.trim()
        // Assuming ToDo constructor is (id, content)
        // Since id is generated by server (or expected to be 0 for new), we pass 0
        const newTodo = new ToDo(0, trimmedContent)
        
        const validation = validateToDoJs(newTodo)
        if (!validation.isValid) {
            setError(validation.errorMessage ?? "Invalid input")
            return
        }

        try {
            await addToDo(newTodo)
            setContent("")
            startTransition(() => {
                // Refresh the list by fetching all again
                setTodosPromise(_fetchAllToDo())
            })
        } catch (err) {
            setError("Failed to add ToDo. Is the server running?")
        }
    }

    return (
        <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-md mx-auto">
                <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-100">
                    <div className="bg-blue-600 px-6 py-8 text-center">
                        <h1 className="text-3xl font-extrabold text-white tracking-tight">
                            Task Manager
                        </h1>
                        <p className="mt-2 text-blue-100 text-sm">
                            Manage your daily activities efficiently
                        </p>
                    </div>

                    <div className="p-6">
                        <form onSubmit={handleAdd} className="mb-8">
                            <label htmlFor="todo-input" className="block text-sm font-semibold text-slate-700 mb-2">
                                Add New Task
                            </label>
                            <div className="flex gap-2">
                                <input
                                    id="todo-input"
                                    type="text"
                                    value={content}
                                    onChange={(e) => setContent(e.target.value)}
                                    placeholder="e.g. Buy groceries..."
                                    className="flex-1 p-3 bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:bg-white transition-all"
                                    disabled={isPending}
                                />
                                <button
                                    type="submit"
                                    disabled={isPending || !content.trim()}
                                    className="px-5 py-3 bg-blue-600 text-white font-bold rounded-lg hover:bg-blue-700 focus:ring-4 focus:ring-blue-200 transition-all disabled:opacity-50 disabled:bg-slate-400"
                                >
                                    {isPending ? (
                                        <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                                    ) : 'Add'}
                                </button>
                            </div>
                            {error && (
                                <p className="mt-2 text-red-500 text-xs font-medium bg-red-50 p-2 rounded border border-red-100 animate-pulse">
                                    {error}
                                </p>
                            )}
                        </form>

                        <div className="relative">
                            <div className="flex items-center justify-between mb-4 px-1">
                                <h2 className="text-lg font-bold text-slate-800">Your Tasks</h2>
                                <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Latest</span>
                            </div>
                            
                            <Suspense fallback={
                                <div className="space-y-3 animate-pulse">
                                    {[1, 2, 3].map(i => (
                                        <div key={i} className="h-14 bg-slate-100 rounded-xl w-full"></div>
                                    ))}
                                </div>
                            }>
                                <ToDoList todosPromise={todosPromise}/>
                            </Suspense>
                        </div>
                    </div>
                    
                    <div className="bg-slate-50 px-6 py-4 border-t border-slate-100 text-center">
                        <p className="text-slate-400 text-[10px] uppercase tracking-widest font-bold">
                            Powered by Kotlin Multiplatform & React
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}
